stages:
  - test
  - release

Test:
  stage: test
  script:
    - .\build.ps1
    - Invoke-psake -buildFile "$PSScriptRoot\build\build.psake.ps1" -taskList Test
  tags:
    - powershell

Release:
  stage: release
  script:
    - .\build.ps1 Publish
  only:
    - stable
  tags:
    - powershell
